version: "3.4"

services:
  project_client:
    build:
      context: frontend/client
    ports:
      - '3000:80'
    environment: 
      - REACT_APP_BACKEND_URL=project-backend.davidpowers.dev
  project_backend:
    build:
      context: backend/
    ports:
      - '5051:80'